/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.roman.week4lab;

import java.text.DecimalFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
* @author Roman K
 */
public class StockGUI extends javax.swing.JFrame {
    // class level reference
    private DefaultListModel<Stock> stockModel; 
    
    /**
     * Creates new form StockGUI
     */
    public StockGUI() {
        // Before GUI is built, create your DefaultListModel object
        stockModel = new DefaultListModel<Stock>();
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrpMainTabs = new javax.swing.JTabbedPane();
        pnlList = new javax.swing.JPanel();
        btnRemove = new javax.swing.JButton();
        jspStrockScroller = new javax.swing.JScrollPane();
        jlsStockList = new javax.swing.JList<>();
        lblProfitLoss = new javax.swing.JLabel();
        txtProfitLoss = new javax.swing.JTextField();
        pnlAddStock = new javax.swing.JPanel();
        lblStockName = new javax.swing.JLabel();
        txtStockName = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        txtPurchasePrice = new javax.swing.JTextField();
        lblPurchasePrice = new javax.swing.JLabel();
        lblCurrentPrice = new javax.swing.JLabel();
        txtCurrentPrice = new javax.swing.JTextField();
        btnAddStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Portfolio Management");

        jrpMainTabs.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        pnlList.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        btnRemove.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        btnRemove.setText("Remove Stock");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jlsStockList.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jlsStockList.setModel(stockModel);
        jlsStockList.setSize(new java.awt.Dimension(39, 130));
        jlsStockList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlsStockListValueChanged(evt);
            }
        });
        jspStrockScroller.setViewportView(jlsStockList);

        lblProfitLoss.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblProfitLoss.setText("Profit / Loss");

        txtProfitLoss.setEditable(false);
        txtProfitLoss.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        txtProfitLoss.setToolTipText("");

        javax.swing.GroupLayout pnlListLayout = new javax.swing.GroupLayout(pnlList);
        pnlList.setLayout(pnlListLayout);
        pnlListLayout.setHorizontalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jspStrockScroller)
                    .addGroup(pnlListLayout.createSequentialGroup()
                        .addComponent(lblProfitLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProfitLoss, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemove)))
                .addContainerGap())
        );
        pnlListLayout.setVerticalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspStrockScroller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemove)
                    .addComponent(lblProfitLoss)
                    .addComponent(txtProfitLoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jrpMainTabs.addTab("List", pnlList);

        lblStockName.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblStockName.setText("Stock name");
        lblStockName.setToolTipText("");

        txtStockName.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        lblQuantity.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblQuantity.setText("Quantity");
        lblQuantity.setToolTipText("");

        txtQuantity.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        txtPurchasePrice.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        lblPurchasePrice.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblPurchasePrice.setText("Purchase Price");
        lblPurchasePrice.setToolTipText("");

        lblCurrentPrice.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblCurrentPrice.setText("Current Price");
        lblCurrentPrice.setToolTipText("");

        txtCurrentPrice.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        btnAddStock.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        btnAddStock.setText("Add Stock");
        btnAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddStockLayout = new javax.swing.GroupLayout(pnlAddStock);
        pnlAddStock.setLayout(pnlAddStockLayout);
        pnlAddStockLayout.setHorizontalGroup(
            pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddStockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddStockLayout.createSequentialGroup()
                        .addComponent(lblPurchasePrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(txtPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddStockLayout.createSequentialGroup()
                        .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStockName)
                            .addComponent(lblQuantity))
                        .addGap(77, 77, 77)
                        .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantity)
                            .addComponent(txtStockName)))
                    .addGroup(pnlAddStockLayout.createSequentialGroup()
                        .addComponent(lblCurrentPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCurrentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddStockLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddStock)))
                .addContainerGap())
        );
        pnlAddStockLayout.setVerticalGroup(
            pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddStockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStockName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPurchasePrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCurrentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurrentPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnAddStock)
                .addContainerGap())
        );

        jrpMainTabs.addTab("Add Stock", pnlAddStock);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jrpMainTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jrpMainTabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // remove selected stock
        int selectedPosition = jlsStockList.getSelectedIndex();
        stockModel.remove(selectedPosition);
        
        txtProfitLoss.setText("");
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStockActionPerformed
        // Validate Input
        if(txtStockName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Error. Please enter the stock's name.", "Invalid Stock Name", JOptionPane.ERROR_MESSAGE);
            txtStockName.requestFocus();
            return;
        }
        
        // get the stock name
        String stockName = txtStockName.getText();
        
        double quantity, purchasePrice, currentPrice;
        
        try
        {
            quantity = Double.parseDouble(txtQuantity.getText());
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this, "Error. Enter numbers only for the quantity.", "Invalid Quantity", JOptionPane.ERROR_MESSAGE);
            txtQuantity.requestFocus();
            return;
        }
        
        try
        {
            purchasePrice = Double.parseDouble(txtPurchasePrice.getText());
        }
        catch (NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this, "Error. Enter numbers only for the purchise price.", "Invalid Purchase Price", JOptionPane.ERROR_MESSAGE);
            txtPurchasePrice.requestFocus();
            return;
        }
        
        try
        {
            currentPrice = Double.parseDouble(txtCurrentPrice.getText());
        }
        catch (NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this, "Error. Enter numbers only for the current price.", "Invalid Current Price", JOptionPane.ERROR_MESSAGE);
            txtCurrentPrice.requestFocus();
            return;
        }
        
        // create stock object
        Stock stk = new Stock(stockName, quantity, purchasePrice, currentPrice);
        
        // add the stock to the default list model -- adds it to JList
        stockModel.addElement(stk);
        
        // reset the form
        
        txtStockName.setText("");
        txtQuantity.setText("");
        txtPurchasePrice.setText("");
        txtCurrentPrice.setText("");
        
        txtStockName.requestFocus();
    }//GEN-LAST:event_btnAddStockActionPerformed

    private void jlsStockListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlsStockListValueChanged
        // get selected stock
        Stock selectedStk = jlsStockList.getSelectedValue();
        
        // show the profit/loss for the 
        if(selectedStk != null)
        {
            double profitLoss = selectedStk.calculateProfitLoss();
            
            DecimalFormat fmt = new DecimalFormat("$#,##0.00");
            if(profitLoss >= 0.0)
                txtProfitLoss.setText(fmt.format(profitLoss));
            else
                txtProfitLoss.setText(fmt.format(profitLoss));
        }
    }//GEN-LAST:event_jlsStockListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStock;
    private javax.swing.JButton btnRemove;
    private javax.swing.JList<Stock> jlsStockList;
    private javax.swing.JTabbedPane jrpMainTabs;
    private javax.swing.JScrollPane jspStrockScroller;
    private javax.swing.JLabel lblCurrentPrice;
    private javax.swing.JLabel lblProfitLoss;
    private javax.swing.JLabel lblPurchasePrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblStockName;
    private javax.swing.JPanel pnlAddStock;
    private javax.swing.JPanel pnlList;
    private javax.swing.JTextField txtCurrentPrice;
    private javax.swing.JTextField txtProfitLoss;
    private javax.swing.JTextField txtPurchasePrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtStockName;
    // End of variables declaration//GEN-END:variables
}
