/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.PizzaOrder;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Roman K
 */
public class Pizza_With_Tabs extends javax.swing.JFrame {

    private PizzaOrder aOrder; 
    private DefaultListModel<PizzaOrder> listModel;
    
    /**
     * Creates new form Pizza_With_Tabs
     */
    public Pizza_With_Tabs() {
        initComponents();
        super.setLocationRelativeTo(null);
        newOrder();
        
        // Before GUI is built, create your DefaultListModel object
        listModel = new DefaultListModel<>();
        lstOrders.setModel(listModel);
    }
    
    private void newOrder() {
        aOrder = new PizzaOrder();  
        clearItems();
    }
    private void setSubTotal() {
        lblSubTotal.setText(aOrder.getTotalCost());
    }
    private void clearItems() {
        txtFirstName.setText("");
        txtLastName.setText("");
        radLarge.setSelected(true);
        chkExtraCheese.setSelected(false);
        chkSausage.setSelected(false);
        chkHam.setSelected(false);
        txtOrderSummary.setText("");
        lblSubTotal.setText("");
        aOrder.clearOrder();
    }
    private void submitOrder() {
        // Validate Input
        if(txtFirstName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Error. Please enter the first Name.", "Invalid First Name", JOptionPane.ERROR_MESSAGE);
            txtFirstName.requestFocus();
            return;
        }
        
        // Validate Input
        if(txtLastName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Error. Please enter the last anme.", "Invalid Last Name", JOptionPane.ERROR_MESSAGE);
            txtLastName.requestFocus();
            return;
        }
        
        StringBuilder str = new StringBuilder();
        if (aOrder != null) {
            str.append("Order submitted\n");
            str.append (aOrder.getOrderInformation());
            listModel.addElement(aOrder);  
        }
        
        txtLastName.setText("");
        txtFirstName.setText("");
        
        txtFirstName.requestFocus();
        
    }
    private void setSize(PizzaOrder.PizzaSize size) {
        aOrder.setPizzaSize(size);
        setSubTotal();
    }
    private void setCheese() {
        if (chkExtraCheese.isSelected()) {
            aOrder.setCheese(true);
        }
        else {
             aOrder.setCheese(false);
        }
        setSubTotal();
    }
    private void setSausage() {
        if (chkSausage.isSelected()) {
            aOrder.setSausage(true);
        }
        else {
             aOrder.setSausage(false);
        }
        setSubTotal();
    }
    private void setHam() {
        if (chkHam.isSelected()) {
           aOrder.setHam(true);
        }
        else {
           aOrder.setHam(false);
        }
        setSubTotal();
    }
    private void setLastName() {
        if (aOrder != null) {
            aOrder.setLastName(txtLastName.getText());
        }
    }
    private void setFirstName() {
        if (aOrder != null) {
            aOrder.setFirstName(txtFirstName.getText());
        }
    }
    private void terminateApplication() {
         int response = JOptionPane.NO_OPTION;
			String prompt = "Do you want to quit the pizza program?";
			String title = "Quit Pizza Program";
			response = JOptionPane.showConfirmDialog(null, prompt, title, 
										  JOptionPane.OK_CANCEL_OPTION, 
										  JOptionPane.QUESTION_MESSAGE);
			if(response == JOptionPane.YES_OPTION) {
				System.exit(0);
			}
    }
    
    private void updateOrder() throws NumberFormatException {
        double value;
        try {
            value = Double.parseDouble(txtTotal.getText());
            aOrder.setTotal(value);
            txaOrder.setText(aOrder.getOrderInformation());
        }
        catch (NumberFormatException ex) {
            String message = txtTotal.getText() + " value is an illegal, enter a number greater than 0";
            JOptionPane.showMessageDialog(null, message, "Illegal total value", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOrderSummary = new javax.swing.JTextArea();
        pnlOutput = new javax.swing.JPanel();
        grpRadio = new javax.swing.ButtonGroup();
        btnUpdateTotal = new javax.swing.JButton();
        txtUpdateOrder = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jplPizzaOrderInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlPerson = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        pnlSize = new javax.swing.JPanel();
        radSmall = new javax.swing.JRadioButton();
        radMedium = new javax.swing.JRadioButton();
        radLarge = new javax.swing.JRadioButton();
        pnlToppings = new javax.swing.JPanel();
        chkExtraCheese = new javax.swing.JCheckBox();
        chkSausage = new javax.swing.JCheckBox();
        chkHam = new javax.swing.JCheckBox();
        btnSumbitOrder = new javax.swing.JButton();
        btnClearItems = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jplOrderSummary = new javax.swing.JPanel();
        jplScrollPanel = new javax.swing.JScrollPane();
        lstOrders = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaOrder = new javax.swing.JTextArea();
        btnDeleteOrder = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        lblWelcome = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        txtOrderSummary.setColumns(20);
        txtOrderSummary.setRows(5);
        jScrollPane1.setViewportView(txtOrderSummary);

        pnlOutput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Your Order Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        javax.swing.GroupLayout pnlOutputLayout = new javax.swing.GroupLayout(pnlOutput);
        pnlOutput.setLayout(pnlOutputLayout);
        pnlOutputLayout.setHorizontalGroup(
            pnlOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );
        pnlOutputLayout.setVerticalGroup(
            pnlOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
        );

        btnUpdateTotal.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnUpdateTotal.setText("Update Order");

        txtUpdateOrder.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jplPizzaOrderInfo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Please enter your name and select your ordering options:");

        pnlPerson.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel2.setText("First Name:");

        txtFirstName.setToolTipText("Enter your first name");
        txtFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusLost(evt);
            }
        });

        jLabel3.setText("Last Name:");

        txtLastName.setToolTipText("Enter your last name");
        txtLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLastNameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlPersonLayout = new javax.swing.GroupLayout(pnlPerson);
        pnlPerson.setLayout(pnlPersonLayout);
        pnlPersonLayout.setHorizontalGroup(
            pnlPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFirstName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPersonLayout.setVerticalGroup(
            pnlPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlSize.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pizza Size (please select one)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        grpRadio.add(radSmall);
        radSmall.setText("Small: $6.99 ");
        radSmall.setToolTipText("Select for small pizza at $6.99");
        radSmall.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radSmallItemStateChanged(evt);
            }
        });

        grpRadio.add(radMedium);
        radMedium.setText("Medium: $9.99  ");
        radMedium.setToolTipText("Select for medium pizza at $9.99");
        radMedium.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radMediumItemStateChanged(evt);
            }
        });

        grpRadio.add(radLarge);
        radLarge.setText("Large:  $12.99");
        radLarge.setToolTipText("Select for large pizza at $12.99");
        radLarge.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radLargeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlSizeLayout = new javax.swing.GroupLayout(pnlSize);
        pnlSize.setLayout(pnlSizeLayout);
        pnlSizeLayout.setHorizontalGroup(
            pnlSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radLarge)
                    .addComponent(radMedium)
                    .addComponent(radSmall))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSizeLayout.setVerticalGroup(
            pnlSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSizeLayout.createSequentialGroup()
                .addComponent(radSmall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radMedium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radLarge))
        );

        pnlToppings.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Toppings (Select as many as you like)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        chkExtraCheese.setText("Extra Cheese: $1.50 ");
        chkExtraCheese.setToolTipText("Select to add extra cheese for $1.50");
        chkExtraCheese.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkExtraCheeseItemStateChanged(evt);
            }
        });

        chkSausage.setText("Sausage: $2.25");
        chkSausage.setToolTipText("Check to add Sausage for $2.25");
        chkSausage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSausageActionPerformed(evt);
            }
        });

        chkHam.setText("Ham: $2.50");
        chkHam.setToolTipText("Check to add Ham for $2.50");
        chkHam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkHamItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlToppingsLayout = new javax.swing.GroupLayout(pnlToppings);
        pnlToppings.setLayout(pnlToppingsLayout);
        pnlToppingsLayout.setHorizontalGroup(
            pnlToppingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToppingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlToppingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkExtraCheese)
                    .addComponent(chkSausage)
                    .addComponent(chkHam))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        pnlToppingsLayout.setVerticalGroup(
            pnlToppingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToppingsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkExtraCheese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSausage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkHam))
        );

        btnSumbitOrder.setText("Submit Order");
        btnSumbitOrder.setToolTipText("Click to show the order total and order summary");
        btnSumbitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumbitOrderActionPerformed(evt);
            }
        });

        btnClearItems.setText("Clear Items");
        btnClearItems.setToolTipText("Click to clear all the order items, the order total, and order summary");
        btnClearItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearItemsActionPerformed(evt);
            }
        });

        btnNew.setText("New Order");
        btnNew.setToolTipText("Clear all items and start new order");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 80));
        lblTotal.setText("Subtotal:");

        lblSubTotal.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(0, 0, 80));
        lblSubTotal.setText("$12.99");

        javax.swing.GroupLayout jplPizzaOrderInfoLayout = new javax.swing.GroupLayout(jplPizzaOrderInfo);
        jplPizzaOrderInfo.setLayout(jplPizzaOrderInfoLayout);
        jplPizzaOrderInfoLayout.setHorizontalGroup(
            jplPizzaOrderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplPizzaOrderInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplPizzaOrderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlToppings, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jplPizzaOrderInfoLayout.createSequentialGroup()
                        .addGroup(jplPizzaOrderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jplPizzaOrderInfoLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jplPizzaOrderInfoLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSumbitOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClearItems, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jplPizzaOrderInfoLayout.setVerticalGroup(
            jplPizzaOrderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplPizzaOrderInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlToppings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jplPizzaOrderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumbitOrder)
                    .addComponent(btnClearItems)
                    .addComponent(lblSubTotal)
                    .addComponent(btnNew)
                    .addComponent(lblTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pizza Order Information", jplPizzaOrderInfo);

        lstOrders.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstOrders.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstOrdersValueChanged(evt);
            }
        });
        jplScrollPanel.setViewportView(lstOrders);

        txaOrder.setColumns(20);
        txaOrder.setRows(5);
        jScrollPane3.setViewportView(txaOrder);

        btnDeleteOrder.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnDeleteOrder.setText("Delete Order");
        btnDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrderActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnUpdate.setText("Update Total");
        btnUpdate.setToolTipText("Click to update the total cost of the order");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtTotal.setToolTipText("Override calculated total price of the order");

        javax.swing.GroupLayout jplOrderSummaryLayout = new javax.swing.GroupLayout(jplOrderSummary);
        jplOrderSummary.setLayout(jplOrderSummaryLayout);
        jplOrderSummaryLayout.setHorizontalGroup(
            jplOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplOrderSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplOrderSummaryLayout.createSequentialGroup()
                        .addComponent(jplScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jplOrderSummaryLayout.createSequentialGroup()
                        .addComponent(btnDeleteOrder)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jplOrderSummaryLayout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal)))
                .addContainerGap())
        );
        jplOrderSummaryLayout.setVerticalGroup(
            jplOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplOrderSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jplScrollPanel)
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addComponent(btnDeleteOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jplOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Order Summary", null, jplOrderSummary, "");

        lblWelcome.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 0, 255));
        lblWelcome.setText("Welcome to Best Pizza!");
        lblWelcome.setName("lblWelcome"); // NOI18N

        btnExit.setText("Exit");
        btnExit.setToolTipText("Click to exit the the Best Pizza order application");
        btnExit.setAutoscrolls(true);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusLost
        setFirstName();
    }//GEN-LAST:event_txtFirstNameFocusLost

    private void txtLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusLost
        setLastName();
    }//GEN-LAST:event_txtLastNameFocusLost

    private void radSmallItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radSmallItemStateChanged
        setSize(PizzaOrder.PizzaSize.Small);
    }//GEN-LAST:event_radSmallItemStateChanged

    private void radMediumItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radMediumItemStateChanged
        setSize(PizzaOrder.PizzaSize.Medium);
    }//GEN-LAST:event_radMediumItemStateChanged

    private void radLargeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radLargeItemStateChanged
        setSize(PizzaOrder.PizzaSize.Large);
    }//GEN-LAST:event_radLargeItemStateChanged

    private void chkExtraCheeseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkExtraCheeseItemStateChanged
        setCheese();
    }//GEN-LAST:event_chkExtraCheeseItemStateChanged

    private void chkSausageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSausageActionPerformed
        setSausage();
    }//GEN-LAST:event_chkSausageActionPerformed

    private void chkHamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkHamItemStateChanged
        setHam();
    }//GEN-LAST:event_chkHamItemStateChanged

    private void btnSumbitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumbitOrderActionPerformed
        submitOrder();
    }//GEN-LAST:event_btnSumbitOrderActionPerformed

    private void btnClearItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearItemsActionPerformed
        clearItems();
    }//GEN-LAST:event_btnClearItemsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        terminateApplication();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        newOrder();
    }//GEN-LAST:event_btnNewActionPerformed

    private void lstOrdersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstOrdersValueChanged
        // when value is selected show the information in the textArea
        
        if (lstOrders.getSelectedIndex() != -1) {
            aOrder = lstOrders.getSelectedValue();
            txaOrder.setText(aOrder.getOrderInformation());
        }
    }//GEN-LAST:event_lstOrdersValueChanged

    private void btnDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrderActionPerformed
        // Delete selected Order
        int item = lstOrders.getSelectedIndex();
        if (item != -1) {
            int response;
            PizzaOrder theOrder = lstOrders.getSelectedValue();
            String prompt = "Are you sure you want to delete order for: " + theOrder.toString();
            response = JOptionPane.showConfirmDialog(null, prompt, "Delete order " + theOrder.toString(), 
                                                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {
                listModel.removeElement(theOrder);
                txaOrder.setText("");
            }
        }
    }//GEN-LAST:event_btnDeleteOrderActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateOrder();
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza_With_Tabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza_With_Tabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza_With_Tabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza_With_Tabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizza_With_Tabs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearItems;
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSumbitOrder;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateTotal;
    private javax.swing.JCheckBox chkExtraCheese;
    private javax.swing.JCheckBox chkHam;
    private javax.swing.JCheckBox chkSausage;
    private javax.swing.ButtonGroup grpRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jplOrderSummary;
    private javax.swing.JPanel jplPizzaOrderInfo;
    private javax.swing.JScrollPane jplScrollPanel;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JList<PizzaOrder> lstOrders;
    private javax.swing.JPanel pnlOutput;
    private javax.swing.JPanel pnlPerson;
    private javax.swing.JPanel pnlSize;
    private javax.swing.JPanel pnlToppings;
    private javax.swing.JRadioButton radLarge;
    private javax.swing.JRadioButton radMedium;
    private javax.swing.JRadioButton radSmall;
    private javax.swing.JTextArea txaOrder;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextArea txtOrderSummary;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUpdateOrder;
    // End of variables declaration//GEN-END:variables
}
